
import setuptools
from distutils.core import setup

setup(
      name             = 'electricityLoadForecasting',
      version          = '0.1.dev0',
      packages         = setuptools.find_packages(),
      scripts          = ['scripts/main_forecasting.py',
                          'scripts/preprocessing_main.py',
                          ],
      author           = 'Ben',
      author_email     = 'bcd6591[at]gmail.com',
      license          = 'MIT License',
      long_description = open('README.txt').read(),
      python_requires  = ">= 3.6",
      install_requires = [
                          'astral==1.2',
                          'chardet',
                          'cvxpy',
                          'datetime',
                          'h5py',
                          'ipdb',
                          'matplotlib',
                          'numpy',
                          'pandas',
                          'prox_tv',
                          'pytz',
                          'scikit-learn',
                          'scipy',
                          'seaborn',
                          'termcolor',
                          'tzlocal',
                          'unidecode',
                          #'openblas',
                          #'sklearn-contrib-py-earth',
                          #'spams',
                          #'rpy2',
                          #'xgboost',
                          ],
      )